### ISSUE TITLE
Implement Builders RFC 0008: Jammy Builders

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/builder-jammy-tiny#1]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/builders/0008-jammy-builders.md)

## Summary
A set of stacks based on the Ubuntu 2022.04 LTS (Jammy Jellyfish) will be maintained by Paketo, per stacks [RFC 0004](https://github.com/paketo-buildpacks/rfcs/blob/da3339d071ffed23c3cd1b374a6bfcefdea7ac70/text/stacks/0004-jammy-jellyfish.md).

## Deliverables
- [x] `builder.toml` that uses Jammy Tiny stack and includes the Paketo Golang and Java Native Image composite buildpacks
- [x] smoke tests
- [x] full repo automation (see https://github.com/paketo-buildpacks/github-config/tree/main/builder)

**Comment by fg-j** [comment]
Blocked by https://github.com/paketo-buildpacks/procfile/issues/111

**Comment by fg-j** [comment]
Blocked by 
- https://github.com/paketo-buildpacks/dep-ensure/pull/250
- https://github.com/paketo-buildpacks/dep/pull/307

**Comment by ForestEckhardt** [comment]
I believe that this done!
