### ISSUE TITLE
The compiled image has Chinese garbled characters

### ISSUE THREAD

**Issue by admintertar** [paketo-buildpacks/builder-jammy-tiny#305]
## Expected Behavior
Chinese characters are garbled, causing SQL to fail to query normally.
![image](https://github.com/paketo-buildpacks/builder-jammy-tiny/assets/29689362/e332f9b8-6f4d-45bc-91ef-a0ca7386783c)

## Current Behavior
Normal query
![image](https://github.com/paketo-buildpacks/builder-jammy-tiny/assets/29689362/ce367362-ca26-46da-a777-4c85dc4ee513)

## Possible Solution
```
paketobuildpacks/builder-jammy-tiny:latest
```
Add multiple encodings

## Steps to Reproduce

#39355

https://github.com/spring-projects/spring-boot/issues/39355

**Comment by dmikusa** [comment]
Closing as the linked issue was marked as closed, see https://github.com/spring-projects/spring-boot/issues/39362#issuecomment-1920452362.
